{
 "title": "Todo App - OTel Metrics",
 "tags": [
  "opentelemetry",
  "todoapp"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "P50",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_server_request_duration_seconds_bucket[5m])) by (le, job))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "P90",
   "type": "stat",
   "gridPos": { "x": 8, "y": 0, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_server_request_duration_seconds_bucket[5m])) by (le, job))",
     "legendFormat": "p90"
    }
   ]
  },
  {
   "title": "Latency P99",
   "type": "stat",
   "gridPos": { "x": 16, "y": 0, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_request_duration_seconds_bucket[5m])) by (le,job))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Requests total",
   "type": "stat",
   "gridPos": { "x": 0, "y": 1, "w": 24, "h": 8 },
   "targets": [
    { "expr": "index_called_request_total", "legendFormat": "index total" },
    { "expr": "add_called_request_total", "legendFormat": "add total" },
    { "expr": "delete_called_request_total", "legendFormat": "delete total" }
   ]
  },
  {
   "title": "Error Requests",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 2, "w": 24, "h": 8 },
   "targets": [
    { "expr": "error_rate_request_total", "legendFormat": "{{http_route}}" }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 3, "w": 24, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_server_request_duration_seconds_sum",
     "legendFormat": "avg latency (s)"
    }
   ]
  }
 ]
}